version: '3.4'
volumes:
    mssql_volume:
services:
  pizzawebapi.web:
    image: ${DOCKER_REGISTRY-}pizzawebapiweb
    ports:
            - 8009:80
    build:
        context: .
        dockerfile: PizzaWebApi/Dockerfile
    depends_on:
        - mssql_docker_db
        - seq
        - seq-input-gelf
  mssql_docker_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
         - 1500:1433
    volumes:
         - mssql_volume:/var/opt/mssql
    environment:
         SA_PASSWORD: "Secret12345"
         ACCEPT_EULA: "Y"
    restart: unless-stopped
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
    depends_on:
      - seq
  seq:
    image: datalust/seq:latest
    ports:
        - 5341:80
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
